<a href="https://colab.research.google.com/github/MubasshirNaib/Machine-learning/blob/main/MLTask01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1:**
Perform suitable experiments with your created numpy arrays with all the properties and functions
mentioned under the “iii. Numpy” section.

In [ ]:
#Using np.array
import numpy as np

Array=np.array([1,2,3,4,5])
print("Array: ",Array);

Array:  [1 2 3 4 5]


In [ ]:
#Creating an array of zeros
Array=np.zeros((3,5))
print(Array)
#Creating an array of ones
Array=np.ones((3,3))
print(Array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of random values
rarray=np.random.random((2,3))
print(rarray)

[[0.43464414 0.39664744 0.02659495]
 [0.5976464  0.17343483 0.87184854]]


In [ ]:
#array with a range of values
aarray=np.arange(10)
print(aarray)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Creating an array with linearly spaced values
l_array=np.linspace(1,10,5)#9/4
print(l_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#copy
o_array=np.array([1,2,3,4,5])
c_array=np.copy(o_array)
print(c_array)

[1 2 3 4 5]


In [ ]:
#Numpy Array Propertie and Attributes
array=np.array([[1,2,3],[4,5,6]])

print("Shape:",array.shape)
print("Number of dimensions:",array.ndim)
print("Number of elements",array.size)
print("Item size(bytes):",array.itemsize)
print("Data Type:",array.dtype)
#Changing data type
array_float=array.astype(np.float64)
print("Array with changes data type:",array_float)
print("New data type:",array_float.dtype)

Shape: (2, 3)
Number of dimensions: 2
Number of elements 6
Item size(bytes): 8
Data Type: int64
Array with changes data type: [[1. 2. 3.]
 [4. 5. 6.]]
New data type: float64


In [ ]:
#indexing
array=np.array([1,2,3,4,5])
print(array[1])
#slicing
print(array[1:4])
#iteration
for i in array:
  print(i,"",end="")


2
[2 3 4]
1 2 3 4 5 

In [ ]:
#arithmatic operation
array1=np.array([1,2,3,4,5])
array2=np.array([3,4,1,2,6])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print("Greater than:",array1>array2)
print("Less then or equal",array1<=array2)

[ 4  6  4  6 11]
[-2 -2  2  2 -1]
[ 3  8  3  8 30]
[0.33333333 0.5        3.         2.         0.83333333]
Greater than: [False False  True  True False]
Less then or equal [ True  True False False  True]


In [ ]:
#Unary Operation
array=np.array([1,2,3,6,7,2,1,4,7,6])
print("Sum:",array.sum())
print("Mean",array.mean())
print("Maximum value:",array.max())
print("Minimum value:",array.min())
print("Standard deviation",array.std())
print("Index of minimum value: ",array.argmin())
print("Index of Maximum value: ",array.argmax())

#reshape
r_array=array.reshape((5,2))
print(r_array)

Sum: 39
Mean 3.9
Maximum value: 7
Minimum value: 1
Standard deviation 2.3
Index of minimum value:  0
Index of Maximum value:  4
[[1 2]
 [3 6]
 [7 2]
 [1 4]
 [7 6]]
